package main

import (
	_ "github.com/RoundRonin/name-subject-to-change/back/docs" // generated by swag
	"github.com/RoundRonin/name-subject-to-change/back/internal/adapters/http"
	"github.com/RoundRonin/name-subject-to-change/back/internal/adapters/repository"
	"github.com/RoundRonin/name-subject-to-change/back/internal/application/user"
	"github.com/RoundRonin/name-subject-to-change/back/internal/platform/db"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title User API
// @version 1.0
// @description API for creating and retrieving users
// @host localhost:8080
// @BasePath /
func main() {
	database := db.NewPostgres()
	repo := repository.NewUserRepository(database)
	svc := user.NewService(repo)
	handler := http.NewUserHandler(svc)

	r := gin.Default()
	handler.RegisterRoutes(r)

	// Swagger endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}
